apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: ghcr.io/cs-muic/scalable-p2-scalable-t3-bbq/controller:latest
        command: ["python"]
        args: ["backend.py"]
        env:
          - name: MINIO_URL
            value: minio:9000
          - name: MINIO_ACCESS_KEY
            value: admin
          - name: MINIO_SECRET_KEY
            value: password
          - name: POSTGRES_USER
            value: dbc
          - name: POSTGRES_PASSWORD
            value: dbc
          - name: POSTGRES_DB
            value: backend:5432
      imagePullSecrets:
        - name: myregistrykey

